### ISSUE TITLE
no default features for actix-web

### ISSUE THREAD

**Issue by robjtede** [vbrandl/actix-request-identifier#1]
If/when the actix-web dependency is updated to v3, the dependency in Cargo.toml should ideally be:

```diff
- actix-web = "3.0.2"
+ actix-web = { version = "3.0.2", default-features = false }
```

**Comment by vbrandl** [comment]
Thanks for the heads up and sorry for the delay. I just updated the `actix-web` dependency to `3.0.0` and disabled default features. The new version `0.2.0` is now [on crates.io](https://crates.io/crates/actix-request-identifier/0.2.0).
